

#Download data:
temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip",temp)

#Extract from zip:
ytrain <- read.table(unz(temp, "UCI HAR Dataset/train/y_train.txt"));
Xtrain <- read.table(unz(temp, "UCI HAR Dataset/train/X_train.txt"));
subjecttrain <- read.table(unz(temp, "UCI HAR Dataset/train/subject_train.txt"));
ytest <- read.table(unz(temp, "UCI HAR Dataset/test/y_test.txt"));
Xtest <- read.table(unz(temp, "UCI HAR Dataset/test/X_test.txt"));
subjecttest <- read.table(unz(temp, "UCI HAR Dataset/test/subject_test.txt"));
features <- read.table(unz(temp, "UCI HAR Dataset/features.txt"));
activitylabels <- read.table(unz(temp, "UCI HAR Dataset/activity_labels.txt"));

unlink(temp)

#Load column names
colnames(Xtrain) <- features[,2];
colnames(Xtest) <- features[,2];

Xtest[,"activity"] <-ytest;
Xtrain[,"activity"] <-ytrain;
Xtest[,"subject"] <- subjecttest[,1];
Xtrain[,"subject"] <- subjecttrain[,1];

#Merge data:
alldata <- rbind(Xtrain, Xtest);
alldata <- merge(alldata, activitylabels, by.x='activity', by.y='V1');
alldata$activity <- alldata$V2;

#Extract relevant columns:
relevantdata <- alldata[, c("subject", "activity")];
relevantdata <- cbind(relevantdata, alldata[, c(grep("mean\\(\\)", colnames(alldata)), grep("std\\(\\)", colnames(alldata)))]);

# Group and calculate mean
attach(relevantdata)
tidydata <- aggregate(relevantdata, by=list(activity = relevantdata$activity, subject = relevantdata$subject), FUN=mean, na.rm=FALSE)
detach(relevantdata)

#Remove columns generated by grouping:
tidydata <- subset(tidydata, select = -c(3,4) )

# Sort
tidydata <- tidydata[order(tidydata$subject, tidydata$activity),]

write.table(tidydata, 'out.txt', row.names = FALSE);

#Write in fixed width format:
if (!is.element('gdata', installed.packages()[,1]))
  install.packages('gdata', dep = TRUE)
require('gdata', character.only = TRUE)

write.fwf(tidydata, 'out2.txt');
